config/routes.rb
Rails.application.routes.draw do

  root 'hotel#index'

  post 'hotel/upload', to: 'hotel#upload'

  resources :hotel do
    resources :directions
    collection do
      get 'checkHotel'
    end
  end

  resources :reservation
  resources :report
  resources :user
  resources :rates do
    member do
      post :saveCells
    end
  end

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base


  def self.get_hotel_categories
    @hotelCats = Hotel.select(:hotel_type).uniq.order(:hotel_type)
  end

  def self.checkHotel( hotel_name )
    return Hotel.where("hotel_name = :hotel", {:hotel => hotel_name } ).count
  end

end

app/controllers/hotel_controller.rb
class HotelController < ApplicationController

  # SHOW ALL HOTELS ON DASHBOARD
  def index
    @hotels = Hotel.all().order(:hotel_name)
    @hotelCategories = Hotel.get_hotel_categories
  end


  # SHOW INDIVIDUAL HOTEL PAGE
  def show
    @id = request.params[:id]
  end


  # FORM PAGE TO CREATE NEW HOTEL
  def new
    @hotel = Hotel.new()
    @hotelCats = Hotel.get_hotel_categories
  end


  # CREATE METHOD
  def create
    @h = Hotel.create( params[:hotel] )
    @h.save()


  end


  # EDIT HOTEL
  def edit
    h = Hotel.find( request.params[:id] )
    @hotel = h
    @hotelCats = Hotel.get_hotel_categories
    @coords = { :lat => h.hotel_lat, :lng => h.hotel_lng }.to_json
  end


  def update
    h = Hotel.find( params[:id] )
    if( h.update( hotel_attributes ) )
      flash[:success] = "#{h.hotel_name} sucessfully updated"
      redirect_to action: :index
    else
      flash[:danger] = "Update unsuccessful"
      redirect_to action: :edit
    end

  end


  # DESTROY METHOD
  def destroy
    id = request.params[:id]
    h = Hotel.find(id).destroy
		flash[:warning] = "Client #{ id } was successfully deleted."
		redirect_to action: :index
  end


  # CHECK TO SEE IF HOTEL NAME EXISTS
  def checkHotel
    h = Hotel.checkHotel( params[:hotel] )
    if h != 0
      render :nothing => true, :status => 409
    else
      render :nothing => true, :status => 200
    end
    return
  end


  # ANONYMOUS IMGUR API UPLOAD THAT RETURNS JSON
  def upload
    respond_to do ||
      name = params[:image_name]
      @api_key = '647a88812a5dc2a'
      c = Curl::Easy.new("http://imgur.com/api/upload.json")
      c.multipart_form_post = true
      c.http_post( Curl::PostField.content('key', @api_key),
                   Curl::PostField.file('image', name ) )
      response = Crack::JSON.parse c.body_str
      raise ImgurError, response["rsp"]["error_msg"] if response["rsp"]["stat"] == "fail"
    end
  end



  private

  def hotel_attributes
      params.require(:hotel).permit(:hotel_name,:hotel_street,:hotel_city,:hotel_state,:hotel_zip,:hotel_phone,
                                    :hotel_email,:hotel_lat,:hotel_lng,:hotel_image_url,:hotel_pets,
                                    :hotel_pet_fee,:hotel_smoking,:hotel_smoking_fee,:hotel_type,
                                    :hotel_region,:hotel_parking_fee )
  end


end

app/helpers/hotel_helper.rb
module HotelHelper
end

app/views/hotel/edit.html.erb
<% content_for :tools do %>


<% end %>

<% content_for :main do %>

  <div class="col-lg-6">

    <%= form_for @hotel, method: :patch, html: { class: "edit_post", id: "js-new-hotel", novalidate: true } do |f| %>

         <fieldset>
         <ul>
          <li class="left">
             <label>Hotel Image Url:</label>
            <%= f.text_field :hotel_image_url,
                              class: 'form-control input-sm',
                              id: 'js-hotel-image-src',
                              placeholder: 'Hotel Image URL'   %>
          </li>
          <li class="right">
           <label>Hotel Region:</label>
           <%= f.select :hotel_type,
                        options_for_select( @hotelCats.collect { |cat| [cat.hotel_type,cat.hotel_type] } ),
                        { include_blank: 'Select hotel region' },
                        class: "form-control input-sm"   %>
          </li>

          <li class="left">
            <div class="form-group">
             <label class="control-label">Hotel Name: <small>(max 350 characters)</small></label>
             <%= f.text_field :hotel_name,
                               class: 'form-control input-sm hotel-location',
                               readonly:true,
                               placeholder: 'Hotel Name',
                               data: { regex: '([A-Z,a-z,0-9,.-])\w+',
                                       validate: '/hotel/checkHotel'  } %>
            </div>
          </li>

          <li class="right">
            <div class="form-group">
             <label class="control-label">Hotel Street:</label>
             <%= f.text_field :hotel_street,
                               class: 'form-control input-sm hotel-location',
                               placeholder: 'Hotel Street',
                               data: { regex: '([A-Z,a-z,0-9,.-])\w+'} %>
            </div>
          </li>
          <li class="left third">
            <div class="form-group">
             <label class="control-label">Hotel City:</label>
             <%= f.text_field :hotel_city,
                               class: 'form-control input-sm hotel-location',
                               placeholder: 'Hotel City',
                               data: { regex: '([A-Za-z0-9,.-])\w+'} %>
            </div>
          </li>
          <li class="middle third">
           <label>Hotel State:</label>
           <select name="hotel_state" class="form-control input-sm">
            <option value="" selected="selected">Select a State</option>
            <option value="AL">Alabama</option>
            <option value="AK">Alaska</option>
            <option value="AZ">Arizona</option>
            <option value="AR">Arkansas</option>
            <option value="CA">California</option>
            <option value="CO">Colorado</option>
            <option value="CT">Connecticut</option>
            <option value="DE">Delaware</option>
            <option value="DC">District Of Columbia</option>
            <option value="FL">Florida</option>
            <option value="GA">Georgia</option>
            <option value="HI">Hawaii</option>
            <option value="ID">Idaho</option>
            <option value="IL">Illinois</option>
            <option value="IN">Indiana</option>
            <option value="IA">Iowa</option>
            <option value="KS">Kansas</option>
            <option value="KY">Kentucky</option>
            <option value="LA">Louisiana</option>
            <option value="ME">Maine</option>
            <option value="MD">Maryland</option>
            <option value="MA">Massachusetts</option>
            <option value="MI">Michigan</option>
            <option value="MN">Minnesota</option>
            <option value="MS">Mississippi</option>
            <option value="MO">Missouri</option>
            <option value="MT">Montana</option>
            <option value="NE">Nebraska</option>
            <option value="NV">Nevada</option>
            <option value="NH">New Hampshire</option>
            <option value="NJ">New Jersey</option>
            <option value="NM">New Mexico</option>
            <option value="NY">New York</option>
            <option value="NC">North Carolina</option>
            <option value="ND">North Dakota</option>
            <option value="OH">Ohio</option>
            <option value="OK">Oklahoma</option>
            <option value="OR">Oregon</option>
            <option value="PA">Pennsylvania</option>
            <option value="RI">Rhode Island</option>
            <option value="SC">South Carolina</option>
            <option value="SD">South Dakota</option>
            <option value="TN">Tennessee</option>
            <option value="TX">Texas</option>
            <option value="UT">Utah</option>
            <option value="VT">Vermont</option>
            <option value="VA">Virginia</option>
            <option value="WA">Washington</option>
            <option value="WV">West Virginia</option>
            <option value="WI">Wisconsin</option>
            <option value="WY">Wyoming</option>
           </select>
          </li>
          <li class="right third">
            <div class="form-group">
             <label class="control-label">Hotel Zip:</label>
             <%= f.number_field :hotel_zip,
                               class: 'form-control input-sm hotel-location',
                               data: { regex: '([0-9-])+'} %>
            </div>
          </li>
          <li class="left third">
            <div class="form-group">
             <label class="control-label">Hotel Phone:</label>
             <%= f.text_field :hotel_phone,
                               class: 'form-control input-sm',
                               placeholder: 'Hotel Phone',
                               data: { regex: '([0-9.()-+])+'} %>
            </div>
          </li>
          <li class="middle third">
            <div class="form-group">
             <label class="control-label">Parking Fee:</label>
             <div class="input-group input-group-sm">
               <span class="input-group-addon">$</span>
               <%= f.number_field :hotel_parking_fee,
                                 class: 'form-control input-sm',
                                 data: { regex: '([0-9.])+'} %>
             </div>
           </div>
          </li>
          <li class="right third ">
           <div class="form-group">
             <label class="control-label">Pet Fee:</label>
             <div class="input-group input-group-sm">
               <span class="input-group-addon">$</span>
               <%= f.number_field :hotel_pet_fee,
                                 class: 'form-control input-sm',
                                 data: { regex: '([0-9.])+'} %>
             </div>
           </div>
          </li>

          <li class="left">
           <label>Latitude:</label>
           <%= f.number_field :hotel_lat,
                             class: 'form-control input-sm',
                             id:'js-hotel-lat',
                             readonly:true %>
          </li>
          <li class="right">
           <label>Longitude:</label>
           <%= f.number_field :hotel_lng,
                             class: 'form-control input-sm',
                             id:'js-hotel-lng',
                             readonly:true %>
          </li>
          <li class="full submit">
            <%= f.button "Create Hotel", class: "btn btn-sm btn-danger" %>
          </li>

        </ul>
        </fieldset>
    <% end %>
  </div>

  <div class="col-lg-6">
    <div id="map-canvas" data-coords="<%= @coords %>" style="height:600px; border:1px solid red;"></div>
  </div>

<% end %>

app/views/hotel/index.html.erb
<% content_for :tools do %>

  <%= link_to( raw('<i class="fa fa-plus"></i> New Hotel'),
               new_hotel_path(),
               class: 'btn btn-default pull-left' ) %>

  <form class="form-inline" role="form" id="js-filter-form">
    <select class="form-control">
      <option value="" selected>-- select --</option>
      <% @hotelCategories.each do |cats| %>
        <option value="<%= cats.hotel_type %>"><%= cats.hotel_type %></option>
      <% end %>
    </select>
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search Hotels">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button"><i class="fa fa-search"></i></button>
      </span>
    </div>
  </form>

<% end %>

<% content_for :main do %>

  <% @hotels.each do |h| %>

    <div class="col-lg-3 col-md-4 col-sm-6" data-filter="<%= h.hotel_name %> <%= h.hotel_type %>">
      <div class="hotel">
        <div class="hotel-img">
          <img src="<%= h.hotel_image_url %>" alt="...">
        </div>
        <div class="hotel-details">
          <strong><%= h.hotel_name %></strong><hr />
          <small><%= h.hotel_street %><br />
          <%= h.hotel_city %> <%= h.hotel_state %> <%= h.hotel_zip %><hr />
          <i class="fa fa-phone"></i>&nbsp;&nbsp; <%= h.hotel_phone %><br />
          Parking: $<%= h.hotel_parking_fee %></small>
        </div>
        <div class="hotel-tools btn-group">
          <%= link_to raw('<i class="fa fa-trash-o"></i>'), hotel_path(h.id), method: :delete, class:"btn btn-lg btn-default", confirm: "Are you sure you want to delete #{h.hotel_name}?" %>
          <%= link_to raw('<i class="fa fa-edit"></i>'), edit_hotel_path(h.id), class:"btn btn-lg btn-default" %>
          <%= link_to raw('<i class="fa fa-map-marker"></i>'), hotel_directions_path(h.id), class:"btn btn-lg btn-default" %>
          <%= link_to raw('<i class="fa fa-plus"></i>'), new_reservation_url(), class:"btn btn-lg btn-default", action: 'new' %>
        </div>
      </div>
    </div>

  <% end %>

<% end %>

app/views/hotel/new.html.erb
<% content_for :tools do %>



<% end %>

<% content_for :main do %>

<div class="col-lg-6">

<!--
<div id="js-image-window" style="display:table-cell;
                                 height:80px;
                                 max-width:80px;
                                 width:80px;
                                 border:2px dashed #ccc;
                                 margin-bottom:15px;
                                 overflow:hidden;"></div>

 <form data-remote="true" method="post" action="/hotel/upload" style="display:table-cell;padding-left:20px; position:relative;">
   <div class="input-group input-group-sm">
     <input type="file" name="hotel-img" class="form-control" style="width:450px;">
     <span class="input-group-btn">
       <button type="submit" class="btn btn-sm btn-default" style="position:absolute; right:0; bottom:0;"><i class="fa fa-upload"></i></button>
     </span>
   </div>
 </form>
-->
<hr />

  <%= form_for @hotel, method: :patch, html: { class: "new-hotel", id: "js-new-hotel" } do |f| %>

   		<fieldset>
     		<ul>
    			<li class="left">
    	 			<label>Hotel Image Url:</label>
            <%= f.text_field :hotel_image_url,
                              class: 'form-control input-sm',
                              id: 'js-hotel-image-src',
                              placeholder: 'Hotel Image URL'   %>
    			</li>
    			<li class="right">
     			<label>Hotel Region:</label>
           <%= f.select :hotel_type,
                        options_for_select( @hotelCats.collect { |cat| [cat.hotel_type,cat.hotel_type] } ),
                        { include_blank: 'Select hotel region' },
                        class: "form-control input-sm"   %>
    			</li>

    			<li class="left">
    				<div class="form-group">
    	 			<label class="control-label">Hotel Name: <small>(max 350 characters)</small></label>
             <%= f.text_field :hotel_name,
                               class: 'form-control input-sm hotel-location',
                               id: 'js-check-hotel-name',
                               placeholder: 'Hotel Name',
                               data: { regex: '([A-Z,a-z,0-9,.-])\w+',
                                       validate: '/hotel/checkHotel'  } %>
    				</div>
    			</li>

    			<li class="right">
    				<div class="form-group">
    	 			<label class="control-label">Hotel Street:</label>
             <%= f.text_field :hotel_street,
                               class: 'form-control input-sm hotel-location',
                               placeholder: 'Hotel Street',
                               data: { regex: '([A-Z,a-z,0-9,.-])\w+'} %>
    				</div>
    			</li>
    			<li class="left third">
    				<div class="form-group">
    	 			<label class="control-label">Hotel City:</label>
             <%= f.text_field :hotel_city,
                               class: 'form-control input-sm hotel-location',
                               placeholder: 'Hotel City',
                               data: { regex: '([A-Za-z0-9,.-])\w+'} %>
    				</div>
    			</li>
    			<li class="middle third">
     			<label>Hotel State:</label>
     			<select name="hotel_state" class="form-control input-sm">
    				<option value="" selected="selected">Select a State</option>
    				<option value="AL">Alabama</option>
    				<option value="AK">Alaska</option>
    				<option value="AZ">Arizona</option>
    				<option value="AR">Arkansas</option>
    				<option value="CA">California</option>
    				<option value="CO">Colorado</option>
    				<option value="CT">Connecticut</option>
    				<option value="DE">Delaware</option>
    				<option value="DC">District Of Columbia</option>
    				<option value="FL">Florida</option>
    				<option value="GA">Georgia</option>
    				<option value="HI">Hawaii</option>
    				<option value="ID">Idaho</option>
    				<option value="IL">Illinois</option>
    				<option value="IN">Indiana</option>
    				<option value="IA">Iowa</option>
    				<option value="KS">Kansas</option>
    				<option value="KY">Kentucky</option>
    				<option value="LA">Louisiana</option>
    				<option value="ME">Maine</option>
    				<option value="MD">Maryland</option>
    				<option value="MA">Massachusetts</option>
    				<option value="MI">Michigan</option>
    				<option value="MN">Minnesota</option>
    				<option value="MS">Mississippi</option>
    				<option value="MO">Missouri</option>
    				<option value="MT">Montana</option>
    				<option value="NE">Nebraska</option>
    				<option value="NV">Nevada</option>
    				<option value="NH">New Hampshire</option>
    				<option value="NJ">New Jersey</option>
    				<option value="NM">New Mexico</option>
    				<option value="NY">New York</option>
    				<option value="NC">North Carolina</option>
    				<option value="ND">North Dakota</option>
    				<option value="OH">Ohio</option>
    				<option value="OK">Oklahoma</option>
    				<option value="OR">Oregon</option>
    				<option value="PA">Pennsylvania</option>
    				<option value="RI">Rhode Island</option>
    				<option value="SC">South Carolina</option>
    				<option value="SD">South Dakota</option>
    				<option value="TN">Tennessee</option>
    				<option value="TX">Texas</option>
    				<option value="UT">Utah</option>
    				<option value="VT">Vermont</option>
    				<option value="VA">Virginia</option>
    				<option value="WA">Washington</option>
    				<option value="WV">West Virginia</option>
    				<option value="WI">Wisconsin</option>
    				<option value="WY">Wyoming</option>
     			</select>
    			</li>
    			<li class="right third">
    				<div class="form-group">
    	 			<label class="control-label">Hotel Zip:</label>
             <%= f.number_field :hotel_zip,
                               class: 'form-control input-sm hotel-location',
                               data: { regex: '([0-9-])+'} %>
    				</div>
    			</li>
    			<li class="left third">
    				<div class="form-group">
    	 			<label class="control-label">Hotel Phone:</label>
             <%= f.text_field :hotel_phone,
                               class: 'form-control input-sm',
                               placeholder: 'Hotel Phone',
                               data: { regex: '([0-9.()-+])+'} %>
    				</div>
    			</li>
    			<li class="middle third">
            <div class="form-group">
             <label class="control-label">Parking Fee:</label>
             <div class="input-group input-group-sm">
               <span class="input-group-addon">$</span>
               <%= f.number_field :hotel_parking_fee,
                                 class: 'form-control input-sm',
                                 data: { regex: '([0-9.])+'} %>
             </div>
           </div>
          </li>
          <li class="right third ">
           <div class="form-group">
             <label class="control-label">Pet Fee:</label>
             <div class="input-group input-group-sm">
               <span class="input-group-addon">$</span>
               <%= f.number_field :hotel_pet_fee,
                                 class: 'form-control input-sm',
                                 data: { regex: '([0-9.])+'} %>
             </div>
           </div>
          </li>


    			<li class="left">
     			<label>Latitude:</label>
           <%= f.number_field :hotel_lat,
                             class: 'form-control input-sm',
                             id:'js-hotel-lat',
                             readonly:true %>
    			</li>
    			<li class="right">
     			<label>Longitude:</label>
           <%= f.number_field :hotel_lng,
                             class: 'form-control input-sm',
                             id:'js-hotel-long',
                             readonly:true %>
    			</li>
    			<li class="full submit">
     			<button value="submit" class="btn btn-sm btn-danger">Create Hotel</button>
    			</li>

    		</ul>
  		</fieldset>

    <% end %>

</div>

<div class="col-lg-6">

    <div id="map-canvas" data-google="" style="height:600px; border:1px solid red;"></div>

</div>

<% end %>